name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Build Docker Image
      run: docker build -t my-lambda .

    - name: Set ECR registry URL
      id: set-ecr-registry-url
      run: echo "::set-output name=registry::${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com"


    - name: Tag Docker Image
      run: docker tag my-lambda:latest ${{ steps.set-ecr-registry-url.outputs.registry }}/my-lambda:latest

    - name: Push Docker Image to ECR
      run: docker push ${{ steps.set-ecr-registry-url.outputs.registry }}/my-lambda:latest